services:
    frontend:
        build: .
        image: reservaja-frontend
        container_name: reservaja_frontend
        ports:
            - "4200:80"
        environment:
            - NODE_ENV=production

